### ISSUE TITLE
[Enhancement] Permit schema scoping

### ISSUE THREAD

**Issue by elyobo** [Mermade/oas-kit#175]
### Checklist

- [x] Linting issue

### Detailed Description

I'd like to ensure that all schema object properties have a truthy `example` property, but I don't think it's possible to limit rules to only match this (happy to have it pointed out if it _is_ possible somehow).

#### Other stuff

Found via speccy.

**Comment by MikeRalphson** [comment]
Because objects under the `properties` map of a `schema` object are also `schema` objects it should be trivial to do exactly what you say you want. Whether this would be ideal in practice is another matter. Consider the following schema fragment:

```yaml
MyObject:
  type: object
  properties:
    id:
      type: integer
    name:
      type: string
```

Such a rule would require examples to be added not only at the `id` and `name` levels, but also at the top level `MyObject`.

Use of `truthy` might also cause problems because many examples might be non-truthy but still present, such as `0` or `null`.

Please feel free to chase up if you try implementing this.

**Comment by elyobo** [comment]
Yes indeed, that is my problem - I don't want it to apply to all schemas, only to some schemas, and there doesn't seem to be a way to limit that scope at the moment.  Would you be open to some sort of approach to apply a scope to rules so that they can be more narrowly targeted than just at the schema level?
