### ISSUE TITLE
Conversion results wrong for large maximum properties

### ISSUE THREAD

**Issue by brhaible** [Mermade/oas-kit#200]
When a maximum property in an OpenAPIv2 input has more than 16 digits, the Mermade converter produces an OpenAPIv3 output that often has a different maximum property.

### Checklist

- [X] Conversion: I have checked my source definition is valid OpenAPI 2.0
- [X] Conversion: On valid OpenAPI 2.0 input, the conversion looks wrong

### Detailed Description

The maximum property in a schema object is defined, in OpenAPIv2 and OpenAPIv3, through a reference to the JSON schema specification. This specification says: "The value of "maximum" MUST be a JSON number.", without any further restriction. In JSON (ECMA-404 section 8), "JSON number" is defined as a sequence of decimal digits with optional sign, decimal point, and exponent. Again no restriction regarding the number of digits.

Observe what happens when the Mermade converter converts such a maximum property: It rounds the value, thereby often producing a different value.

Test case with 151-digit numbers:

```
$ swagger2openapi -o large-maximum.v3m.json large-maximum.v2.json
```
The correct result is large-maximum.v3.json.

#### Other stuff

[large-maximum.v2.json.gz](https://github.com/Mermade/oas-kit/files/3580728/large-maximum.v2.json.gz)
[large-maximum.v3m.json.gz](https://github.com/Mermade/oas-kit/files/3580729/large-maximum.v3m.json.gz)
[large-maximum.v3.json.gz](https://github.com/Mermade/oas-kit/files/3580730/large-maximum.v3.json.gz)

**Comment by MikeRalphson** [comment]
From [RFC8259](https://tools.ietf.org/html/rfc8259):

> This specification allows implementations to set limits on the range
   and precision of numbers accepted.  Since software that implements
   IEEE 754 binary64 (double precision) numbers [IEEE754] is generally
   available and widely used, good interoperability can be achieved by
   implementations that expect no more precision or range than these
   provide, in the sense that implementations will approximate JSON
   numbers within the expected precision.  A JSON number such as 1E400
   or 3.141592653589793238462643383279 may indicate potential
   interoperability problems, since it suggests that the software that
   created it expects receiving software to have greater capabilities
   for numeric magnitude and precision than is widely available.

   Note that when such software is used, numbers that are integers and
   are in the range [-(2**53)+1, (2**53)-1] are interoperable in the
   sense that implementations will agree exactly on their numeric
   values.

As `oas-kit` is written in JavaScript, the restrictions on JavaScript object values take precedence.

**Comment by brhaible** [comment]
It's interesting to see that the text that you cite is contained in [RFC 8259](https://tools.ietf.org/html/rfc8259) but not in [ECMA 404](https://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf)...
